const CONSTS =
{
  PREFECTURES: {
    name: '旅行先',
    items: [
      { "code": 1, "name": "北海道"},
      { "code": 2, "name": "青森県"},
      { "code": 3, "name": "岩手県"},
      { "code": 4, "name": "宮城県"},
      { "code": 5, "name": "秋田県"},
      { "code": 6, "name": "山形県"},
      { "code": 7, "name": "福島県"},
      { "code": 8, "name": "茨城県"},
      { "code": 9, "name": "栃木県"},
      { "code": 10, "name": "群馬県"},
      { "code": 11, "name": "埼玉県"},
      { "code": 12, "name": "千葉県"},
      { "code": 13, "name": "東京都"},
      { "code": 14, "name": "神奈川県"},
      { "code": 15, "name": "新潟県"},
      { "code": 16, "name": "富山県"},
      { "code": 17, "name": "石川県"},
      { "code": 18, "name": "福井県"},
      { "code": 19, "name": "山梨県"},
      { "code": 20, "name": "長野県"},
      { "code": 21, "name": "岐阜県"},
      { "code": 22, "name": "静岡県"},
      { "code": 23, "name": "愛知県"},
      { "code": 24, "name": "三重県"},
      { "code": 25, "name": "滋賀県"},
      { "code": 26, "name": "京都府"},
      { "code": 27, "name": "大阪府"},
      { "code": 28, "name": "兵庫県"},
      { "code": 29, "name": "奈良県"},
      { "code": 30, "name": "和歌山県"},
      { "code": 31, "name": "鳥取県"},
      { "code": 32, "name": "島根県"},
      { "code": 33, "name": "岡山県"},
      { "code": 34, "name": "広島県"},
      { "code": 35, "name": "山口県"},
      { "code": 36, "name": "徳島県"},
      { "code": 37, "name": "香川県"},
      { "code": 38, "name": "愛媛県"},
      { "code": 39, "name": "高知県"},
      { "code": 40, "name": "福岡県"},
      { "code": 41, "name": "佐賀県"},
      { "code": 42, "name": "長崎県"},
      { "code": 43, "name": "熊本県"},
      { "code": 44, "name": "大分県"},
      { "code": 45, "name": "宮崎県"},
      { "code": 46, "name": "鹿児島県"},
      { "code": 47, "name": "沖縄県"},
    ],
  },
  LUNCH: {
    name: '今日のランチ',
    items: [
      { "code": 1, "name": "インドカレー"},
      { "code": 2, "name": "焼肉"},
      { "code": 3, "name": "寿司"},
      { "code": 4, "name": "台湾料理"},
      { "code": 5, "name": "中華"},
      { "code": 6, "name": "牛丼"},
      { "code": 7, "name": "タイ料理"},
      { "code": 8, "name": "定食屋"},
      { "code": 9, "name": "ハンバーガー"},
      { "code": 10, "name": "ステーキ"},
      { "code": 11, "name": "カレー"},
      { "code": 12, "name": "二郎系ラーメン"},
      { "code": 13, "name": "とんこつラーメン"},
      { "code": 14, "name": "塩ラーメン"},
      { "code": 15, "name": "つけ麺"},
      { "code": 16, "name": "家系ラーメン"},
      { "code": 17, "name": "味噌ラーメン"},
      { "code": 18, "name": "醤油ラーメン"},
      { "code": 19, "name": "そば"},
      { "code": 20, "name": "うどん"},
      { "code": 21, "name": "唐揚げ"},
      { "code": 22, "name": "お好み焼き"},
      { "code": 23, "name": "沖縄料理"},
      { "code": 24, "name": "台湾料理"},
      { "code": 25, "name": "ピザ"},
      { "code": 26, "name": "パスタ"},
      { "code": 27, "name": "シュラスコ"},
      { "code": 28, "name": "韓国料理"},
      { "code": 29, "name": "麻婆豆腐"},
      { "code": 30, "name": "うなぎ"},
      { "code": 31, "name": "タコス"},
      { "code": 32, "name": "ジンギスカン"},
      { "code": 33, "name": "サムギョプサル"},
      { "code": 34, "name": "パンケーキ"},
      { "code": 35, "name": "ファミレス"},
      { "code": 36, "name": "弁当テイクアウト"},
      { "code": 37, "name": "ホテルでバイキング"},
      { "code": 38, "name": "しゃぶしゃぶ・すき焼き"},
      { "code": 39, "name": "スープカレー"},
      { "code": 40, "name": "うなぎ"},
      { "code": 41, "name": "もんじゃ焼き"},
      { "code": 42, "name": "天丼"},
      { "code": 43, "name": "カツ丼"},
      { "code": 44, "name": "とんかつ"},
      { "code": 45, "name": "生姜焼き"},
      { "code": 46, "name": "天ぷら"},
    ],
  },
  DINNER: {
    name: '今日の晩御飯の献立',
    items: [
      { "code": 1, "name": "キムチ鍋"},
      { "code": 2, "name": "カレー"},
      { "code": 3, "name": "ミートソース"},
      { "code": 4, "name": "カルボナーラ"},
      { "code": 5, "name": "オムライス"},
      { "code": 6, "name": "生姜焼き"},
      { "code": 7, "name": "肉じゃが"},
      { "code": 8, "name": "ハンバーグ"},
      { "code": 9, "name": "から揚げ"},
      { "code": 10, "name": "餃子"},
      { "code": 11, "name": "豚汁"},
      { "code": 12, "name": "炊き込みご飯"},
      { "code": 13, "name": "卵焼きと味噌汁"},
      { "code": 14, "name": "麻婆豆腐"},
      { "code": 15, "name": "回鍋肉"},
      { "code": 16, "name": "ロールキャベツ"},
      { "code": 17, "name": "煮魚"},
      { "code": 18, "name": "焼き魚"},
      { "code": 19, "name": "天ぷら"},
      { "code": 20, "name": "うどん"},
      { "code": 21, "name": "手巻き / ちらし寿"},
      { "code": 22, "name": "三色そぼろ丼"},
      { "code": 23, "name": "チャーハン"},
      { "code": 24, "name": "親子丼"},
      { "code": 25, "name": "カツ丼"},
      { "code": 26, "name": "野菜炒め"},
      { "code": 27, "name": "グラタン"},
      { "code": 28, "name": "すき焼き"},
      { "code": 29, "name": "とんかつ"},
      { "code": 30, "name": "春巻き"},
      { "code": 31, "name": "ピーマンの肉詰め"},
      { "code": 32, "name": "オムレツ"},
      { "code": 33, "name": "クリームシチュー"},
      { "code": 34, "name": "ビーフシチュー"},
      { "code": 35, "name": "角煮"},
      { "code": 36, "name": "さばの味噌煮"},
      { "code": 37, "name": "豚キムチ炒め"},
    ],
  },
};

